opencv_project/landmark_detection/urls.py
from django.urls import path
from landmark_detection import views


app_name = "landmark_detection"

urlpatterns = [
    path("", views.index, name="index"),
    path("detect_landmark/", views.detect_landmark, name="detect_landmark"),
    # path("detect_landmark/<int:photo_id>/", views.detect_landmark, name="detect_landmark"),
]

opencv_project/opencv_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.urls import path, include


urlpatterns = [
    path('', include('photo_lab.urls', namespace='photo_lab')),
    path(
      'landmark_detection/',
      include('landmark_detection.urls', namespace='landmark_detection')
    ),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opencv_project/photo_lab/urls.py
from django.urls import path
from photo_lab import views


app_name = "photo_lab"

urlpatterns = [
    path("", views.index, name="index"),
    path("photo/<int:photo_id>/", views.photo_options, name="photo_options"),
    path("process_photo/<int:photo_id>/", views.process_photo, name="process_photo"),
]

opencv_project/photo_lab/models.py
from django.db import models

class Photo(models.Model):
    title = models.CharField("Title", max_length=30)
    image = models.ImageField("Photo", upload_to="photo_images", blank=True)
    annotation = models.CharField("Annotation", max_length=30, blank=True, null=True)
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Uploaded"
    )

    class Meta:
        verbose_name = "photo"
        verbose_name_plural = "photos"
        ordering = ("-created_at",)

    def __str__(self):
        return self.title[:20] + '...' if len(self.title) > 20 else self.title

opencv_project/landmark_detection/views.py
import os
from django.conf import settings
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
from .opencv_utils import detect_object


def index(request):
    return render(request, "landmark_detection/index.html")


def detect_landmark(request):
    if request.method == "POST" and request.FILES.get("image"):
        uploaded_image = request.FILES["image"]
        selected_option = request.POST.get("options")

        fs = FileSystemStorage()
        filename = fs.save(uploaded_image.name, uploaded_image)
        image_path = os.path.join(settings.MEDIA_ROOT, filename)

        if selected_option == "detect_hq":
            xml_file = os.path.join(settings.BASE_DIR, "cascades", "myhqdetector.xml")
        elif selected_option == "detect_mun":
            xml_file = os.path.join(settings.BASE_DIR, "cascades", "myhousedetector.xml")
        
        processed_image_url = detect_object(image_path, xml_file)

        return render(request, "landmark_detection/detection_result.html", {
            "processed_image_url": processed_image_url,
            "filename": uploaded_image.name,
        })
    
    return render(request, "landmark_detection/detection_result.html", {
        "error": "No image uploaded.",
    })

opencv_project/photo_lab/views.py
import os
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from .models import Photo
from .opencv_utils import (
    reduce_noise,
    reduce_blur,
)
from .cv_similarity_retrieval import retrieve_similar_images
from .cv_assess_quality import assess_quality
from .cv_detect_faces import detect_faces
from .cv_classify_daytime import classify_daytime


def index(request):
    if request.method == "POST" and request.FILES.get("image"):
        image = request.FILES["image"]
        title = image.name
        photo = Photo.objects.create(title=title, image=image)
        return redirect("photo_lab:photo_options", photo_id=photo.id)
    return render(request, "photo_lab/index.html")


def photo_options(request, photo_id):
    photo = get_object_or_404(Photo, id=photo_id)
    return render(request, "photo_lab/options.html", {"photo": photo})


def process_photo(request, photo_id):
    photo = get_object_or_404(Photo, id=photo_id)
    operations = request.POST.getlist("operations")
    processed_url = photo.image.url
    daytime_results = {}
    quality_assessment = None
    quality_visuals = []
    compare = False
    similar_photos = []
    face_results = {}

    if "detect_faces" in operations:
        detection_result = detect_faces(photo.image.path)

        face_results = {
            "haar": {
                "url": settings.MEDIA_URL + detection_result["haar"]["path"],
                "time": round(detection_result["haar"]["time"], 3),
                "faces": detection_result["haar"]["faces"],
            },
            "dlib": {
                "url": settings.MEDIA_URL + detection_result["dlib"]["path"],
                "time": round(detection_result["dlib"]["time"], 3),
                "faces": detection_result["dlib"]["faces"],
            },
            "dnn": {
                "url": settings.MEDIA_URL + detection_result["dnn"]["path"],
                "time": round(detection_result["dnn"]["time"], 3),
                "faces": detection_result["dnn"]["faces"],
            },
        }

    if "detect_daytime" in operations:
        daytime_results = classify_daytime(photo.image.path)
        labels = [v["label"] for v in daytime_results.values()]
        time_of_day = "Day" if labels.count("day") > labels.count("night") else "Night"

    if "reduce_noise" in operations:
        processed_url = reduce_noise(photo.image.path)
        compare = True

    if "reduce_blur" in operations:
        processed_url = reduce_blur(photo.image.path)
        compare = True
    
    if "assess_quality" in operations:
        quality_assessment, quality_visuals = assess_quality(photo.image.path)

    if "similarity_retrieval" in operations:
        all_photos = Photo.objects.filter(annotation="sim").exclude(id=photo.id)
        results = retrieve_similar_images(photo.image.path, all_photos, top_k=3)
        
        for score, detail, similar_photo in results:
            similar_photos.append({
                "photo": similar_photo,
                "score": score,
                "details": detail
            })

    return render(request, "photo_lab/result.html", {
        "original": photo.image.url,
        "processed": processed_url,
        "title": photo.title,
        "daytime_results": daytime_results,
        "quality_assessment": quality_assessment,
        "quality_visuals": quality_visuals,
        "photo": photo,
        "compare": compare,
        "similar_photos": similar_photos,
        "face_results": face_results,
    })

opencv_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% comment %} <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image"> {% endcomment %}
    {% comment %} <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}"> {% endcomment %}
    {% comment %} <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}"> {% endcomment %}
    {% comment %} <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}"> {% endcomment %}
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

opencv_project/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© OpenCV Project</p>    
</footer>

opencv_project/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url "photo_lab:index" %}">
        {% comment %} <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt=""> {% endcomment %}
        OpenCV Project
      </a>

      <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link" href="{% url "landmark_detection:index" %}">Landmark detection</a>
            {% comment %} <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a> {% endcomment %}
          </li>
          <li class="nav-item">
            {% comment %} <a class="nav-link {% if view_name == 'pages:rules' %} text-white {% endif %}" href="{% url 'pages:rules' %}">
              Правила
            </a> {% endcomment %}
      </ul>      
    </div>
  </nav> 
</header>

opencv_project/templates/includes/media_card.html
<div class="card" style="width: 40rem;">
  <div class="card-body">
    {% if photo.image %}
        <a href="{{ photo.image.url }}" target="_blank">
          <img 
            class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" 
            src="{{ photo.image.url }}"
            style="width: 100%; height: 450px; object-fit: cover;"
          >
        </a>
      {% endif %}
    <h5 class="card-title">{{ photo.title }}</h5>
    
    <a href="{% url 'photo_lab:detect_faces' photo.id %}" class="btn btn-primary mt-2">
      Face detection
    </a>
    <a href="{% url 'photo_lab:annotate_objects' photo.id %}" class="btn btn-primary mt-2">
      Objects annotation
    </a>
  </div>
</div>

opencv_project/templates/landmark_detection/detection_result.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h2>Detection Result</h2>

    {% if error %}
      <div class="alert alert-danger mt-3">{{ error }}</div>
    {% elif processed_image_url %}
      <div class="text-start mt-3">
        <img 
          src="{{ processed_image_url }}"
          class="img-fluid border"
          alt="Detected Image"
          style="max-width: 900px; max-height: 500px;"
        >
      </div>
    {% else %}
      <p>No image detected or failed to load image.</p>
    {% endif %}

    <div class="mt-4 text-start">
      <a href="{% url 'landmark_detection:index' %}" class="btn btn-secondary" style="width: 150px;">← Back</a>
    </div>
  </div>
{% endblock %}

opencv_project/templates/landmark_detection/index.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-4">
    <h2>Landmark Detection</h2>

    <p class="mb-4 mt-5">
      <strong>How to use:</strong> Upload an image using the form below and choose a landmark to detect.
    </p>

    <form 
      method="post"
      enctype="multipart/form-data"
      class="mb-3 p-4 border rounded bg-light shadow-sm"
      action="{% url 'landmark_detection:detect_landmark' %}"
      style="width: 100%; max-width: 620px;"
    >
      {% csrf_token %}

      <div class="mb-3">
        <label for="image" class="form-label">Upload image</label>
        <input type="file" class="form-control" id="image" name="image" required>
      </div>

      <div class="mb-3">
        <label class="form-label">Choose building to detect:</label>
        <div class="form-check">
          <input class="form-check-input" type="radio" value="detect_hq" id="detect_hq" name="options">
          <label class="form-check-label" for="detect_hq">
            Detect AldarHQ
          </label>
        </div>
        <div class="form-check">
          <input class="form-check-input" type="radio" value="detect_mun" id="detect_mun" name="options">
          <label class="form-check-label" for="detect_mun">
            Detect Al Muneera Building
          </label>
        </div>
      </div>

      <button type="submit" class="btn btn-primary" style="width: 150px;">Detect</button>
    </form>
  </div>
{% endblock %}
    {% comment %} {% if photos %}
      <div class="row">
        {% for photo in photos %}
          <div class="col-md-4 mb-4">
            <div class="card">
                <img 
                  src="{{ photo.image.url }}" 
                  class="card-img-top fixed-image" 
                  alt="{{ photo.title }}"
                >

              <div class="card-body text-center">
                <form action="{% url 'landmark_detection:detect_landmark' photo.id %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-sm btn-outline-primary">
                    Landmark Detect
                  </button>
                </form>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    {% else %}
      <p>No images found.</p>
    {% endif %} {% endcomment %}
  

  {% comment %} <style>
    .fixed-image {
      height: 300px;
      object-fit: cover;
      width: 100%;
    }
  </style> {% endcomment %}

opencv_project/templates/photo_lab/index.html
{% extends "base.html" %}
{% block title %}
  Photo Lab
{% endblock %}
{% block content %}
  <h1 class="mb-5">Photo Lab</h1>
    <p class="mb-4" style="width: 100%; max-width: 800px;">
      <strong>How to use:</strong> First, upload an image using the form below. After that, choose the task you want to perform.
    </p>

    <form method="post" enctype="multipart/form-data" class="mb-5 p-4 border rounded bg-light shadow-sm" style="width: 100%; max-width: 800px;">
      {% csrf_token %}
      <div class="mb-3">
        <label for="image" class="form-label">Upload image</label>
        <input type="file" class="form-control" id="image" name="image" required>
      </div>
      <button type="submit" class="btn btn-primary">Upload</button>
    </form>
{% endblock %}

opencv_project/templates/photo_lab/options.html
{% extends "base.html" %}

{% block title %}
  Choose option for — {{ photo.title }}
{% endblock %}

{% block content %}
<div class="container mt-5">
  <h1 class="mb-4">What do you want to do with the image?</h1>

  <div class="card shadow-sm" style="max-width: 720px">
    <div class="card-body" style="padding: 20px;">
      <form method="post" action="{% url 'photo_lab:process_photo' photo.id %}">
        {% csrf_token %}
        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" value="detect_faces" id="detect_faces" name="operations">
          <label class="form-check-label" for="detect_faces">
            Face Detection
          </label>
        </div>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" value="detect_daytime" id="detect_daytime" name="operations">
          <label class="form-check-label" for="detect_daytime">
            Daytime Detection
          </label>
        </div>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" value="reduce_noise" id="reduce_noise" name="operations">
          <label class="form-check-label" for="reduce_noise">
            Reduce noise
          </label>
        </div>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" value="reduce_blur" id="reduce_blur" name="operations">
          <label class="form-check-label" for="reduce_blur">
            Reduce blur
          </label>
        </div>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" value="assess_quality" id="assess_quality" name="operations">
          <label class="form-check-label" for="assess_quality">
            Quality Assessment
          </label>
        </div>

        <div class="form-check mb-2">
          <input class="form-check-input" type="radio" value="similarity_retrieval" id="similarity_retrieval" name="operations">
          <label class="form-check-label" for="similarity_retrieval">
            Find similar images
          </label>
        </div>

        <button type="submit" class="btn btn-primary mt-3">Confirm</button>
      </form>
    </div>

    <img 
      src="{{ photo.image.url }}" 
      class="card-img-top img-fluid" 
      alt="{{ photo.title }}" 
      style="width: 100%;  margin-top: 15px; height: 500px; object-fit: contain;"
    >
  </div>

  <a href="{% url 'photo_lab:index' %}" class="btn btn-primary mt-3">&larr; Upload next image</a>
</div>
{% endblock %}

opencv_project/templates/photo_lab/result.html
{% extends "base.html" %}

{% block title %}{{ title|default:"Result" }}{% endblock %}

{% block content %}
<div class="container">

  {% if face_results %}
    <h2 class="mb-4">Face Detection Results</h2>
    <div class="row text-center mb-4">
      <div class="col-md-4">
        <h5>Haar Cascade</h5>
        <p>Detected Faces: {{ face_results.haar.faces }}</p>
        <p>Time: {{ face_results.haar.time|floatformat:2 }}s</p>
        <a href="{{ face_results.haar.url }}" target="_blank">
          <img src="{{ face_results.haar.url }}" class="img-fluid border" alt="Haar Detection">
        </a>
      </div>
      <div class="col-md-4">
        <h5>HOG + SVM (Dlib)</h5>
        <p>Detected Faces: {{ face_results.dlib.faces }}</p>
        <p>Time: {{ face_results.dlib.time|floatformat:2 }}s</p>
        <a href="{{ face_results.dlib.url }}" target="_blank">
          <img src="{{ face_results.dlib.url }}" class="img-fluid border" alt="HOG Detection">
        </a>
      </div>
      <div class="col-md-4">
        <h5>DNN (Caffe)</h5>
        <p>Detected Faces: {{ face_results.dnn.faces }}</p>
        <p>Time: {{ face_results.dnn.time|floatformat:2 }}s</p>
        <a href="{{ face_results.dnn.url }}" target="_blank">
          <img src="{{ face_results.dnn.url }}" class="img-fluid border" alt="DNN Detection">
        </a>
      </div>
    </div>
  {% endif %}


  {% if compare %}
    <h2 class="mb-4">Original vs. Processed</h2>
    <div class="row">
      <div class="col-md-6">
        <h5>Original image</h5>
        <a href="{{ original }}" target="_blank">
          <img src="{{ original }}" class="img-fluid border" alt="Original image">
        </a>
      </div>
      <div class="col-md-6">
        <h5>Processed image</h5>
        <a href="{{ processed }}" target="_blank">
          <img src="{{ processed }}" class="img-fluid border" alt="Processed Image">
        </a>
      </div>
    </div>
  {% elif similar_photos  %}
    <h2>Original and Similar Images</h2>
  <div class="row mb-4">
    <div class="col-md-3 text-center">
      <h5>Original</h5>
      <a href="{{ original }}" target="_blank">
        <img src="{{ original }}" alt="Original Image" class="img-fluid border" />
      </a>
    </div>

    {% for item in similar_photos %}
    <div class="col-md-3 text-center">
      <h5>Similar #{{ forloop.counter }}</h5>
      <a href="{{ item.photo.image.url }}" target="_blank">
        <img src="{{ item.photo.image.url }}" alt="Similar Image {{ forloop.counter }}" class="img-fluid border" />
      </a>
      <p>Score: {{ item.score|floatformat:2 }}</p>
    </div>
    {% endfor %}

    <div class="similarity-metrics mt-4" style="background:#f8f9fa; padding:15px; border-radius:5px; font-family: monospace; white-space: pre-wrap;">
  <strong>Similarity Metrics Breakdown:</strong>

  {% for item in similar_photos %}
    Match #{{ forloop.counter }}: {{ item.photo.image.url }}
    {% for method, mscore in item.details.items %}
      {{ method|ljust:8 }}: {{ mscore|floatformat:4 }}
    {% endfor %}
      --> Overall similarity = (hist + ssim + orb + templ + edges + contours) / 6
                            = {{ item.score|floatformat:4 }}
  {% endfor %}
</div>
  {% elif not face_results and not compare and not similar_photos %}
    <div class="text-start" style="max-width: 600px;">
      <h2 class="mb-4">Result of image processing</h2>
      <a href="{{ processed }}" target="_blank">
        <img 
          src="{{ processed }}" 
          class="img-fluid mb-3"
          style="width: 100%; height: auto; object-fit: cover;"
          alt="Processed Image"
        >
      </a>

      {% if daytime_results %}
        <h2 class="mb-4">Time-of-Day Classification Results</h2>
        <div class="row text-center">
          {% for method, data in daytime_results.items %}
            <div class="col-md-4 mb-3">
              <h5>{{ method|upper }}</h5>
              <p><strong>Mean:</strong> {{ data.mean|floatformat:2 }}</p>
              <p><strong>Threshold:</strong> {{ data.threshold }}</p>
              <p>
                <strong>Result:</strong>
                <span style="color: {% if data.label == 'day' %}green{% else %}darkblue{% endif %}; font-weight: bold;">
                  {{ data.label|title }}
                </span>
              </p>
            </div>
          {% endfor %}
        </div>
      {% endif %}


      {% if quality_assessment %}
        <h3 class="mt-5">Quality assessment</h3>
        <ul>
          {% for key, value in quality_assessment.items %}
            <li><strong>{{ key }}:</strong> {{ value }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% if quality_visuals %}
        <h3 class="mt-5">Quality assessment plots</h3>
        <ul>
          {% for title, img_url in quality_visuals.items %}
            <li class="mt-3">
              <strong>{{ title }}</strong><br>
              <img src="{{ img_url }}" alt="{{ title }}" style="max-width: 100%; height: auto;">
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
  {% endif %}

  <a href="{% url 'photo_lab:photo_options' photo.id %}" class="btn btn-secondary mt-4" style="width: 150px; text-align: center;">← Back</a>
</div>
{% endblock %}

opencv_project/templates/photo_lab/sharpened_result.html
{% extends "base.html" %}

{% block title %}Sharpened Image{% endblock %}

{% block content %}
<div class="container">
  <h2 class="mb-4">Original vs. Sharpened Image</h2>

  <div class="row">
    <div class="col-md-6">
      <h5>Original Image</h5>
      <a href="{{ original_photo.image.url }}" target="_blank">
        <img 
          src="{{ original_photo.image.url }}" 
          class="img-fluid border"
          alt="Original Image"
        >
      </a>
    </div>

    <div class="col-md-6">
      <h5>Sharpened Image</h5>
      <a href="{{ sharpened_image_url }}" target="_blank">
        <img 
          src="{{ sharpened_image_url }}" 
          class="img-fluid border"
          alt="Sharpened Image"
        >
      </a>
    </div>
  </div>

  <a href="{% url 'photo_lab:index' %}" class="btn btn-secondary mt-4">← Back</a>
</div>
{% endblock %}

opencv_project/templates/photo_lab/smoothed_result.html
{% extends "base.html" %}

{% block title %}Smoothed Image{% endblock %}

{% block content %}
<div class="container">
  <h2 class="mb-4">Original vs. Smoothed Image</h2>

  <div class="row">
    <div class="col-md-6">
      <h5>Original Image</h5>
      <a href="{{ original_photo.image.url }}" target="_blank">
        <img 
          src="{{ original_photo.image.url }}" 
          class="img-fluid border"
          alt="Original Image"
        >
      </a>
    </div>

    <div class="col-md-6">
      <h5>Smoothed Image</h5>
      <a href="{{ smoothed_image_url }}" target="_blank">
        <img 
          src="{{ smoothed_image_url }}" 
          class="img-fluid border"
          alt="Smoothed Image"
        >
      </a>
    </div>
  </div>

  <a href="{% url 'photo_lab:index' %}" class="btn btn-secondary mt-4">← Back</a>
</div>
{% endblock %}